### YamlMime:ManagedReference
apiRules:
- exclude:
    uidRegex: ^System\.
    type: Type
- exclude:
    hasAttribute:
      uid: System.Runtime.CompilerServices.CompilerGeneratedAttribute
    type: Type
